title: PoliSciPy
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  View on GitHub: https://github.com/eolesinski/poliscipy

color_scheme: custom

# External navigation links
nav_external_links:
  - title: PoliSciPy on GitHub
    url: https://github.com/eolesinski/poliscipy